import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { ROOT, outputDir, statePath, ensureDir } from "./paths.mjs";
import { setupGithubRepo } from "./github.mjs";
import { deployGasWebApp } from "./gas-webapp.mjs";

export function loadState(clientId) {
  const p = statePath(clientId);
  if (!fs.existsSync(p)) return { phase: "start" };
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

export function saveState(clientId, state) {
  ensureDir(outputDir(clientId));
  fs.writeFileSync(statePath(clientId), JSON.stringify(state, null, 2));
}

export function appendLog(logFn, message) {
  const line = `[${new Date().toISOString()}] ${message}`;
  logFn(line);
  return line;
}

export function preflight(cfg, log, dryRun) {
  appendLog(log, "Phase 0 · 前置檢查");
  const required = ["clientId", "clientName", "district", "fiscalYear"];
  for (const key of required) {
    if (!cfg[key]) throw new Error(`client.config 缺少欄位：${key}`);
  }
  if (!dryRun) {
    execSync("node -v", { encoding: "utf8" });
    execSync("npm -v", { encoding: "utf8" });
    try {
      execSync("npx clasp -v", { cwd: path.join(ROOT, "gas"), encoding: "utf8", stdio: "pipe" });
      appendLog(log, "✓ clasp 可用");
    } catch {
      throw new Error("請先執行：npm run gas:login");
    }
    if (!fs.existsSync(path.join(ROOT, "node_modules"))) {
      appendLog(log, "執行 npm install …");
      execSync("npm install", { cwd: ROOT, stdio: "inherit" });
    }
  }
  appendLog(log, "✓ 前置檢查通過");
}

export async function phaseGithub(cfg, log, dryRun) {
  if (!cfg.github?.enabled) {
    appendLog(log, "⊘ GitHub 略過（github.enabled = false）");
    return null;
  }
  if (dryRun) {
    appendLog(log, "（dry-run）將建立私有 GitHub 倉庫");
    return { htmlUrl: `https://github.com/${cfg.github.org}/${cfg.github.repoName}` };
  }
  return setupGithubRepo(cfg, (msg) => appendLog(log, msg));
}

export function phaseGas(cfg, log, dryRun) {
  appendLog(log, "Phase 1 · Google Apps Script + 試算表");
  const gasDir = path.join(ROOT, "gas");
  const claspJson = path.join(gasDir, ".clasp.json");

  if (!fs.existsSync(claspJson) && !dryRun) {
    const title = cfg.google?.gasProjectTitle || `${cfg.clientName} GAS`;
    appendLog(log, `建立 GAS 專案：${title}`);
    execSync(
      `npx clasp create --type webapp --title ${JSON.stringify(title)} --rootDir src`,
      { cwd: gasDir, stdio: "inherit" },
    );
  } else {
    appendLog(log, "✓ GAS 專案已連結");
  }

  if (!dryRun) {
    appendLog(log, "推送 GAS 原始碼 …");
    execSync("npx clasp push", { cwd: gasDir, stdio: "inherit" });
  }

  const bootstrapPayload = JSON.stringify({
    clientId: cfg.clientId,
    clientName: cfg.clientName,
    clientCode: cfg.clientCode,
    district: cfg.district,
    fiscalYear: cfg.fiscalYear,
    workspaceId: cfg.workspaceId,
    encodePrefix: cfg.encodePrefix,
    spreadsheetName: cfg.spreadsheetName,
  });

  appendLog(log, "執行 bootstrapForClient …");
  let bootstrapResult = {};
  if (!dryRun) {
    const out = execSync(
      `npx clasp run bootstrapForClient --params ${JSON.stringify([bootstrapPayload])}`,
      { cwd: gasDir, encoding: "utf8", stdio: "pipe" },
    ).trim();
    try {
      bootstrapResult = JSON.parse(out);
      appendLog(log, `✓ 試算表：${bootstrapResult.spreadsheet_url || bootstrapResult.spreadsheet_id}`);
    } catch {
      appendLog(log, out);
      appendLog(log, "⚠ 請從輸出手動複製 spreadsheet_id / api_token");
    }
  }

  return bootstrapResult;
}

export async function phaseGasWebApp(log, dryRun) {
  return deployGasWebApp((msg) => appendLog(log, msg), dryRun);
}

export function needsGasWebAppUrl(state, gasWebAppUrl) {
  return !gasWebAppUrl && !state.gasWebAppUrl;
}

export function resolveGasWebAppUrl(state) {
  if (state.gasWebAppUrl) return state.gasWebAppUrl;
  const envPath = path.join(ROOT, ".env.local");
  if (!fs.existsSync(envPath)) return "";
  const m = fs.readFileSync(envPath, "utf8").match(/^GAS_WEB_APP_URL=(.+)$/m);
  if (m?.[1] && !m[1].includes("PLACEHOLDER")) return m[1].trim();
  return "";
}

export function writeEnvLocal(cfg, bootstrap, gasWebAppUrl) {
  const allowed = (cfg.access?.allowedEmails || []).join(",");
  const owners = (cfg.access?.ownerEmails || []).join(",");
  const appUrl = cfg.vercel?.productionUrl || "http://localhost:3000";

  const content = `# Generated by install:client — ${cfg.clientId}
GAS_WEB_APP_URL=${gasWebAppUrl}
GAS_API_TOKEN=${bootstrap.api_token || ""}
GAS_WORKSPACE_ID=${bootstrap.workspace_id || cfg.workspaceId}
GAS_SPREADSHEET_ID=${bootstrap.spreadsheet_id || ""}

GOOGLE_ALLOWED_EMAILS=${allowed}
GOOGLE_OWNER_EMAILS=${owners}

NEXT_PUBLIC_APP_URL=${appUrl}
`;
  fs.writeFileSync(path.join(ROOT, ".env.local"), content);
}

export function phaseVercel(cfg, log, dryRun) {
  if (!cfg.vercel?.enabled) {
    appendLog(log, "⊘ Vercel 略過（vercel.enabled = false）");
    return;
  }
  appendLog(log, "Phase 3 · Vercel 部署");
  const scope = cfg.vercel.teamSlug;
  const project = cfg.vercel.projectName;
  const appUrl = cfg.vercel.productionUrl;

  const run = (cmd) => {
    appendLog(log, `▶ ${cmd}`);
    if (!dryRun) execSync(cmd, { cwd: ROOT, stdio: "inherit" });
  };

  run("rm -rf .vercel");

  const envPairs = [
    ["GAS_WEB_APP_URL", process.env.GAS_WEB_APP_URL],
    ["GAS_API_TOKEN", process.env.GAS_API_TOKEN],
    ["GAS_WORKSPACE_ID", process.env.GAS_WORKSPACE_ID],
    ["GAS_SPREADSHEET_ID", process.env.GAS_SPREADSHEET_ID],
    ["GOOGLE_ALLOWED_EMAILS", (cfg.access?.allowedEmails || []).join(",")],
    ["GOOGLE_OWNER_EMAILS", (cfg.access?.ownerEmails || []).join(",")],
    ["NEXT_PUBLIC_APP_URL", appUrl],
  ];

  if (!dryRun) {
    run(`npx vercel link --yes --scope ${scope} --project ${project}`);
    for (const [key, val] of envPairs) {
      if (!val) continue;
      for (const env of ["production", "preview", "development"]) {
        try {
          execSync(
            `printf %s ${JSON.stringify(val)} | npx vercel env add ${key} ${env} --scope ${scope} --yes`,
            { cwd: ROOT, stdio: "pipe" },
          );
        } catch {
          // env may already exist
        }
      }
    }
    run(`npx vercel --prod --yes --scope ${scope}`);
  }
  appendLog(log, `✓ Vercel Production：${appUrl}`);
}

export function phaseHandoff(cfg, bootstrap, gasWebAppUrl, github, log) {
  appendLog(log, "Phase 4 · 生成交接包");
  const outDir = outputDir(cfg.clientId);
  ensureDir(outDir);

  const credentials = {
    clientId: cfg.clientId,
    generatedAt: new Date().toISOString(),
    spreadsheetUrl: bootstrap.spreadsheet_url,
    spreadsheetId: bootstrap.spreadsheet_id,
    workspaceId: bootstrap.workspace_id || cfg.workspaceId,
    gasWebAppUrl,
    apiToken: bootstrap.api_token,
    vercelUrl: cfg.vercel?.productionUrl,
    googleAccount: cfg.google?.accountEmail,
    githubRepo: github?.htmlUrl,
  };

  fs.writeFileSync(path.join(outDir, "credentials.json"), JSON.stringify(credentials, null, 2));

  const handoff = `# ${cfg.clientName} — 系統交接清單

> 合約／專案：${cfg.handoff?.contractRef || "—"}  
> 交接日期：${new Date().toISOString().slice(0, 10)}  
> 技術支援至：${cfg.handoff?.supportUntil || "—"}

## 1. 交付項目

| 項目 | 內容 |
|------|------|
| GitHub 倉庫 | ${github?.htmlUrl || "—"} |
| 管理網站 | ${cfg.vercel?.productionUrl || "本機 npm run dev"} |
| Google 試算表 | ${bootstrap.spreadsheet_url || "—"} |
| 操作說明書 | docs/system-operation-manual.md |
| 架構說明書 | docs/system-architecture.md |

## 2. 登入方式

- **承辦管理者**：${cfg.vercel?.productionUrl || ""}/login
- 輸入 Gmail：${(cfg.access?.allowedEmails || []).join("、")}

## 3. 驗收檢查

- [ ] 可登入管理後台
- [ ] 名冊可看到個案資料
- [ ] GitHub 倉庫為 Private
- [ ] 試算表與網站資料一致

## 4. 聯絡

${cfg.handoff?.contactEmail || "—"}

*由 install:client 自動產生*
`;

  fs.writeFileSync(path.join(outDir, "handoff.md"), handoff);
  appendLog(log, `✓ 交接包：installer/output/${cfg.clientId}/`);
}

export function loadEnvLocal() {
  const envPath = path.join(ROOT, ".env.local");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) process.env[m[1]] = m[2];
  }
}

export function normalizeConfig(raw) {
  const clientCode = raw.clientCode || raw.clientId?.split("-")[0]?.toUpperCase() || "CL";
  const fiscalYear = String(raw.fiscalYear || "115");
  return {
    ...raw,
    clientCode,
    fiscalYear,
    workspaceId: raw.workspaceId || `WS-${clientCode}-${fiscalYear}`,
    encodePrefix: raw.encodePrefix || `${clientCode}-${fiscalYear}`,
    spreadsheetName:
      raw.spreadsheetName ||
      `${raw.district}_${fiscalYear}年_獨居長者訪查_主檔`,
    github: {
      enabled: raw.github?.enabled ?? true,
      org: raw.github?.org || "yongheelderly0826-design",
      templateRepo:
        raw.github?.templateRepo || "yongheelderly0826-design/Elder-Visit-Platform",
      repoName: raw.github?.repoName || `elder-visit-${raw.clientId}`,
      private: raw.github?.private !== false,
      description: raw.github?.description,
    },
    vercel: {
      enabled: raw.vercel?.enabled ?? true,
      teamSlug: raw.vercel?.teamSlug || "yongheelderly0826-design",
      projectName: raw.vercel?.projectName || `elder-visit-${raw.clientId}`,
      productionUrl:
        raw.vercel?.productionUrl ||
        `https://elder-visit-${raw.clientId}.vercel.app`,
    },
  };
}
