export const sitemapSections = [
  {
    title: "啟動與註冊",
    description: "從個人帳號進入系統，完成單位與工作空間關聯。",
    roles: ["新使用者", "工作空間管理者"],
    entryCondition: "使用者尚未加入工作空間，或管理者需要審核新成員。",
    completionResult: "使用者取得 Workspace membership，登入後會依角色看到對應畫面。",
    steps: [
      "使用者註冊帳號並完成 Email 驗證",
      "選擇或申請所屬單位 Unit",
      "申請加入 Workspace 並提出預期角色",
      "管理者在使用者管理頁審核",
      "核准後建立 Workspace membership 與角色權限",
    ],
    commonQuestions: [
      "如果使用者看不到功能，先檢查是否已審核通過。",
      "如果進錯工作空間，應回到工作空間選擇頁重新確認。",
    ],
    relatedLinks: [
      { label: "使用者管理", href: "/workspace/users" },
      { label: "權限管理", href: "/workspace/permissions" },
      { label: "工作空間", href: "/workspace/select" },
    ],
    href: "/workspace/users",
  },
  {
    title: "治理設定",
    description: "管理工作空間、角色、同意書、藍圖版本與方案限制。",
    roles: ["工作空間擁有者", "承辦管理者", "資料治理人員"],
    entryCondition: "工作空間已建立，準備設定模組、權限、同意治理與 API 邊界。",
    completionResult: "系統有清楚的責任歸屬、權限矩陣、保存期限與 API 維護邊界。",
    steps: [
      "設定 Workspace 責任人、模組與保存期限",
      "建立縣市政府表單、個資同意書與訪查人員保密同意書版本",
      "檢視角色與操作權限矩陣",
      "管理同意範圍、撤回與匯出用途",
      "產生 Blueprint migration preview",
      "在參數頁檢查 API 權限、資料邊界與 RLS 待辦",
      "檢查方案限制、連線參數與日誌保存",
    ],
    commonQuestions: [
      "如果某人不能操作，先看權限管理的 CRUD 矩陣。",
      "如果 API 可被呼叫但資料不該外流，下一步要補 Supabase RLS。",
    ],
    relatedLinks: [
      { label: "空間規則", href: "/workspace/settings" },
      { label: "表單", href: "/manager/forms" },
      { label: "權限管理", href: "/workspace/permissions" },
      { label: "參數", href: "/system/status" },
      { label: "API 維運", href: "/system/status#api" },
    ],
    href: "/workspace/settings",
  },
  {
    title: "訪查營運",
    description: "從名冊匯入、派案到訪員填報的日常工作流。",
    roles: ["承辦管理者", "督導", "訪員"],
    entryCondition: "已有長者名冊，或需要建立本期訪查任務。",
    completionResult: "訪查任務被派出，訪員可在任務頁填報並送出紀錄。",
    steps: [
      "匯入長者名冊並檢查欄位對應",
      "確認本期採用的縣市政府生活關懷表版本",
      "在個案名冊檢視風險與狀態",
      "依區域、容量與訓練狀態產生派案建議",
      "訪員登入後查看任務並填報訪查表",
      "離線草稿可暫存後送出",
    ],
    commonQuestions: [
      "如果派案按鈕不能按，檢查角色是否有 assignment.confirm。",
      "如果訪員看不到任務，檢查是否已被派案且登入角色是否為訪員。",
    ],
    relatedLinks: [
      { label: "名冊", href: "/manager/cases" },
      { label: "名冊匯入", href: "/manager/cases" },
      { label: "派案", href: "/manager/assignments" },
      { label: "表單", href: "/manager/forms" },
      { label: "訪員任務", href: "/visitor/tasks" },
    ],
    href: "/manager/cases",
  },
  {
    title: "實務訪查作業流程",
    description: "依實際現場作業：名冊交承辦、承辦派案、訪員填報、未遇三次、承辦審核、長官確認、匯出中央系統資料。",
    roles: ["承辦管理者", "督導", "訪員"],
    entryCondition: "縣市或公所已有待訪名冊，並需要依民政、社政與里別進行實務派案。",
    completionResult: "訪查完成或未遇三次結案，資料經承辦與長官確認後，可產出匯入中央系統的 Excel 或成果報表。",
    steps: [
      "名冊由承辦匯入或建立，系統保存案號、姓名、地址、行政區與里別。",
      "承辦依里別、民政/社政身分、共訪需求與訪員工作量進行派案。",
      "派案前檢查督導與訪員身分資料，包含個人資料、訪員證、受訓日期與匯款帳戶。",
      "訪員進入任務後填寫縣市政府生活關懷表、個資同意書與必要保密同意書。",
      "訪員拍照或上傳門口、本人、環境等照片時，系統同步取得定位。",
      "若訪視未遇，第一次與第二次不得結案，需安排下一次訪視；第三次未遇可送督導確認後結案。",
      "承辦或督導審核訪查內容、照片、定位、同意書與未遇紀錄。",
      "長官確認後，通過資料可進入核銷、成果匯出與中央系統 Excel 匯入資料。",
      "核銷依參數費率計算：訪視費 180 元、資料處理費 30 元，費率可在參數頁維護。",
    ],
    commonQuestions: [
      "目前名冊、派案、訪員填報、稽核、核銷與匯出都有操作入口。",
      "中央系統 Excel 目前是匯出資料與模板預覽，尚未串接外部中央系統 API。",
      "督導/訪員完整身分管理已進入資料模型與派案規則，下一步要把維護表單接到正式 Supabase 資料。",
    ],
    relatedLinks: [
      { label: "名冊", href: "/manager/cases" },
      { label: "派案管理", href: "/manager/assignments" },
      { label: "訪員任務", href: "/visitor/tasks" },
      { label: "稽核", href: "/manager/audit" },
      { label: "匯出與核銷", href: "/manager/exports" },
      { label: "核銷費率", href: "/system/status" },
    ],
    href: "/manager/assignments",
  },
  {
    title: "派案流程",
    description: "將待訪名冊轉成訪員任務，並用規則分數輔助承辦與督導做最後確認。",
    roles: ["承辦管理者", "督導", "訪員"],
    entryCondition: "長者名冊已建立，且本期已有待訪排程或需要重新分派訪員。",
    completionResult: "派案被確認後，訪員端任務清單會出現對應訪查，並保留派案理由與覆核紀錄。",
    steps: [
      "建立或匯入長者名冊與訪查排程",
      "系統讀取長者行政區、里別、風險等級與是否需要民政/社政共訪",
      "檢查訪員今日容量、服務里別、民政/社政身分、訪員證、受訓日期與匯款資料",
      "依同里別、同區域、身分符合、共訪搭配、容量、訓練與風險優先產生派案分數",
      "有提醒項目的派案先送主管覆核",
      "承辦或主管確認後，任務送到訪員端",
    ],
    commonQuestions: [
      "分數越高代表越適合，但仍保留人工確認與覆核。",
      "訪員容量已滿或缺少訓練時，系統會提示不要直接派案。",
      "正式上線後派案確認需寫入不可竄改的活動紀錄。",
    ],
    relatedLinks: [
      { label: "派案管理", href: "/manager/assignments" },
      { label: "名冊", href: "/manager/cases" },
      { label: "訪員任務", href: "/visitor/tasks" },
      { label: "使用者管理", href: "/workspace/users" },
    ],
    href: "/manager/assignments",
  },
  {
    title: "稽核與核銷",
    description: "主管覆核訪查紀錄，通過後建立核銷草稿與批次。",
    roles: ["督導", "稽核人員", "承辦管理者"],
    entryCondition: "訪員已送出訪查紀錄，系統可進行阻擋項目與提醒項目檢核。",
    completionResult: "訪查紀錄完成覆核，符合條件者進入核銷草稿與批次。",
    steps: [
      "稽核規則產生阻擋項目與提醒項目",
      "未遇案件確認是否已達第三次，未達第三次不得結案核銷",
      "具核准權限的角色核准或退回補件",
      "核准後產生核銷草稿",
      "依核銷費率參數計算訪視費 180 元與資料處理費 30 元",
      "具核銷權限的角色鎖定核銷",
      "彙整鎖定項目成核銷批次",
    ],
    commonQuestions: [
      "阻擋項目未通過不能核准，需退回補件。",
      "核銷鎖定後應避免直接修改金額，解鎖需留下原因。",
    ],
    relatedLinks: [
      { label: "稽核", href: "/manager/audit" },
      { label: "匯出與核銷", href: "/manager/exports" },
      { label: "流程引擎", href: "/manager/engines" },
    ],
    href: "/manager/audit",
  },
  {
    title: "成果與匯出",
    description: "依同意治理與方案限制產生報表與成果監控。",
    roles: ["承辦管理者", "督導", "唯讀檢視者"],
    entryCondition: "訪查與稽核資料已累積，需要檢視成果、產生報表或贊助成果。",
    completionResult: "產生符合權限、同意範圍與方案限制的成果資料。",
    steps: [
      "檢視 KPI 成果與未達標提醒",
      "建立核銷批次",
      "選擇匯出模板與匯出用途",
      "依同意治理規則自動遮罩個資",
      "產生 CSV / XLSX 報表內容",
      "承辦或長官確認後，輸出可匯入中央系統的 Excel 資料",
    ],
    commonQuestions: [
      "如果匯出被擋，檢查方案限制與 exports.create 權限。",
      "贊助成果只能使用彙整或匿名化資料，不應輸出可識別個案。",
    ],
    relatedLinks: [
      { label: "KPI", href: "/manager/kpi" },
      { label: "匯出", href: "/manager/exports" },
      { label: "同意治理", href: "/manager/consent" },
      { label: "贊助設定", href: "/workspace/settings" },
    ],
    href: "/manager/exports",
  },
  {
    title: "異常與通知",
    description: "處理急迫健康、安全風險、聯絡失敗與資料問題。",
    roles: ["訪員", "督導", "承辦管理者"],
    entryCondition: "訪查、稽核或資料檢查過程發現需要追蹤的異常事件。",
    completionResult: "異常事件被通知、處理、結案，並保留追蹤紀錄。",
    steps: [
      "訪員或稽核產生異常通報",
      "系統依模板建立督導通知",
      "管理者標記通知或結案",
      "異常資料進入 KPI 與稽核追蹤",
      "保存處理紀錄供日後查核",
    ],
    commonQuestions: [
      "通知督導屬代表性溝通，正式串外部通道前需確認權限。",
      "異常結案不代表刪除紀錄，仍需保留查核軌跡。",
    ],
    relatedLinks: [
      { label: "通報", href: "/manager/notifications" },
      { label: "KPI", href: "/manager/kpi" },
      { label: "API 維運", href: "/system/status#api" },
    ],
    href: "/manager/notifications",
  },
  {
    title: "志工出勤簽到",
    description: "12 組志工：外勤掃集合點 QR，公所內勤刷身分證條碼，月底匯出 Excel。",
    roles: ["承辦管理者", "督導", "訪員"],
    entryCondition: "志工已建檔（姓名、身分證、組別）。外勤無電腦，公所有掃描器。",
    completionResult: "每筆出勤有簽到/簽退時間，可下載月結 Excel 再匯入既有系統。",
    steps: [
      "承辦先在志工出勤頁建立名冊，指定 12 組之一",
      "列印各組集合點 QR 海報張貼現場",
      "外勤志工用手機開啟簽到頁，輸入身分證登入（記錄身分與組別）",
      "掃描集合點 QR，系統記錄簽到或簽退時間",
      "公所內勤由承辦登入刷證櫃台，掃描身分證條碼完成簽到退",
      "月底下載出勤 Excel，再匯入公所既有系統",
    ],
    commonQuestions: [
      "這與訪查到宅簽到不同；訪查簽到仍綁派案，志工出勤綁組別與地點 QR。",
      "官方月結欄位若與下載檔不同，把範本給承辦即可對欄。",
    ],
    relatedLinks: [
      { label: "志工出勤", href: "/manager/attendance" },
      { label: "外勤掃碼", href: "/volunteer/clock" },
      { label: "公所刷證", href: "/office/kiosk" },
    ],
    href: "/manager/attendance",
  },
];
