import type { ElderCase, VisitSchedule } from "@/lib/domain/types";

export const yh75DemoImportBatchCode = "YH-115-075-PILOT-100";

type SourceRow = {
  sourceRowNumber: number;
  name: string;
  gender: string | null;
  birthDate: string | null;
  nationalId: string | null;
  phone: string | null;
  mobilePhone: string | null;
  lineIdStatus: string | null;
  lineIdNote: string | null;
  emergencyContactName: string | null;
  emergencyContactRelationship: string | null;
  emergencyContactPhone: string | null;
  householdCity: string;
  householdDistrict: string;
  householdVillage: string;
  householdAddress: string;
  residenceCity: string | null;
  residenceDistrict: string | null;
  residenceVillage: string | null;
  residenceAddress: string;
  residenceAddressNote: string | null;
  solitaryStatus: string;
};

const sourceRows: SourceRow[] = [
  {
    "sourceRowNumber": 2,
    "name": "董家暖",
    "gender": null,
    "birthDate": "1912-01-01",
    "nationalId": "C100131450",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永安里",
    "householdAddress": "新北市永和區永安里9鄰安樂路２７２巷１３號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永安里9鄰安樂路２７２巷１３號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 3,
    "name": "邢姜維蘭",
    "gender": null,
    "birthDate": "1912-01-01",
    "nationalId": "A201616765",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民治里",
    "householdAddress": "新北市永和區民治里14鄰民治街９７巷４號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民治里14鄰民治街９７巷４號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 4,
    "name": "謝有京",
    "gender": null,
    "birthDate": "1912-01-01",
    "nationalId": "A203012381",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "仁愛里",
    "householdAddress": "新北市永和區仁愛里13鄰保福路二段４６號六樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區仁愛里13鄰保福路二段４６號六樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 5,
    "name": "蘇薛香",
    "gender": null,
    "birthDate": "1915-01-01",
    "nationalId": "A201003535",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀成里",
    "householdAddress": "新北市永和區秀成里9鄰成功路一段９３巷７號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀成里9鄰成功路一段９３巷７號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 6,
    "name": "萬億先",
    "gender": null,
    "birthDate": "1919-01-01",
    "nationalId": "E201260123",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "安和里",
    "householdAddress": "新北市永和區安和里5鄰中和路５１９巷１６號九樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區安和里5鄰中和路５１９巷１６號九樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 7,
    "name": "孫執中",
    "gender": null,
    "birthDate": "1919-01-01",
    "nationalId": "F100983475",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民本里",
    "householdAddress": "新北市永和區民本里15鄰民樂街８１號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民本里15鄰民樂街８１號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 8,
    "name": "郭洪玉眉",
    "gender": null,
    "birthDate": "1920-01-01",
    "nationalId": "F200949680",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "信義里",
    "householdAddress": "新北市永和區信義里8鄰永和路二段３９號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區信義里8鄰永和路二段３９號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 9,
    "name": "林德文",
    "gender": null,
    "birthDate": "1920-01-01",
    "nationalId": "A103224441",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "安和里",
    "householdAddress": "新北市永和區安和里5鄰中和路５３５號六樓之１１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區安和里5鄰中和路５３５號六樓之１１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 10,
    "name": "雲天蔚",
    "gender": null,
    "birthDate": "1921-01-01",
    "nationalId": "F102795339",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 11,
    "name": "王德輝",
    "gender": null,
    "birthDate": "1921-01-01",
    "nationalId": "H100690413",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀元里",
    "householdAddress": "新北市永和區秀元里17鄰得和路３７３巷３１弄１１號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀元里17鄰得和路３７３巷３１弄１１號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 12,
    "name": "王又曦",
    "gender": null,
    "birthDate": "1921-01-01",
    "nationalId": "F231607877",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 13,
    "name": "談斌",
    "gender": null,
    "birthDate": "1921-01-01",
    "nationalId": "F104255249",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 14,
    "name": "易延清",
    "gender": null,
    "birthDate": "1921-01-01",
    "nationalId": "F202480353",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民治里",
    "householdAddress": "新北市永和區民治里3鄰中正路２８６巷８號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民治里3鄰中正路２８６巷８號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 15,
    "name": "凌雲秀",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "H200276157",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民族里",
    "householdAddress": "新北市永和區民族里22鄰民有街５９號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民族里22鄰民有街５９號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 16,
    "name": "張啟福",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "F100938738",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "頂溪里",
    "householdAddress": "新北市永和區頂溪里5鄰文化路１６巷５弄３４號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區頂溪里5鄰文化路１６巷５弄３４號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 17,
    "name": "李呂瑞雲",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "B200923986",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 18,
    "name": "黃明禮",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "F102820775",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀林里",
    "householdAddress": "新北市永和區秀林里7鄰秀朗路二段１４３號十一樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀林里7鄰秀朗路二段１４３號十一樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 19,
    "name": "陳樓",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "A100144124",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "潭墘里",
    "householdAddress": "新北市永和區潭墘里19鄰安樂路１９４巷２９號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區潭墘里19鄰安樂路１９４巷２９號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 20,
    "name": "戴豪興",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "F129128010",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 21,
    "name": "盧子安",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "E102428412",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 22,
    "name": "翁品英",
    "gender": null,
    "birthDate": "1922-01-01",
    "nationalId": "A202992175",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "保平里",
    "householdAddress": "新北市永和區保平里24鄰中山路一段２８１巷２弄１０號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區保平里24鄰中山路一段２８１巷２弄１０號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 23,
    "name": "張均惠",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "A100561045",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "安和里",
    "householdAddress": "新北市永和區安和里13鄰水源街４３巷４號五樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區安和里13鄰水源街４３巷４號五樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 24,
    "name": "趙福民",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F104423336",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 25,
    "name": "江奶玉",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F100981999",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "仁愛里",
    "householdAddress": "新北市永和區仁愛里8鄰保福路二段７６號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區仁愛里8鄰保福路二段７６號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 26,
    "name": "劉光明",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "A102571263",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民生里",
    "householdAddress": "新北市永和區民生里8鄰民生路６７巷１０號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民生里8鄰民生路６７巷１０號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 27,
    "name": "胡鶴亭",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "A100093088",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "竹林里",
    "householdAddress": "新北市永和區竹林里12鄰豫溪街１６５號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區竹林里12鄰豫溪街１６５號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 28,
    "name": "李遠",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F100932405",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "信義里",
    "householdAddress": "新北市永和區信義里1鄰信義路１巷４號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區信義里1鄰信義路１巷４號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 29,
    "name": "邱瑞萱",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F104259014",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 30,
    "name": "趙霞飛",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F104266402",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "竹林里",
    "householdAddress": "新北市永和區竹林里13鄰豫溪街１３０巷２號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區竹林里13鄰豫溪街１３０巷２號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 31,
    "name": "洪天發",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F102836371",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "潭墘里",
    "householdAddress": "新北市永和區潭墘里15鄰安樂路１０４巷１號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區潭墘里15鄰安樂路１０４巷１號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 32,
    "name": "胡秀華",
    "gender": null,
    "birthDate": "1923-01-01",
    "nationalId": "F203449276",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "和平里",
    "householdAddress": "新北市永和區和平里18鄰永貞路３５５巷３號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區和平里18鄰永貞路３５５巷３號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 33,
    "name": "吳葉健民",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "E200638547",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永興里",
    "householdAddress": "新北市永和區永興里3鄰豫溪街１３７號之３七樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永興里3鄰豫溪街１３７號之３七樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 34,
    "name": "陳學良",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F103763046",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 35,
    "name": "佘江蘭",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F202467869",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀成里",
    "householdAddress": "新北市永和區秀成里10鄰成功路一段９３巷２１弄３號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀成里10鄰成功路一段９３巷２１弄３號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 36,
    "name": "許意讚",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F100966894",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "和平里",
    "householdAddress": "新北市永和區和平里3鄰保福路一段５３號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區和平里3鄰保福路一段５３號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 37,
    "name": "林陳菜妹",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F202505060",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "潭安里",
    "householdAddress": "新北市永和區潭安里19鄰得和路５７號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區潭安里19鄰得和路５７號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 38,
    "name": "賀金荷蓮",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F202506585",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "福和里",
    "householdAddress": "新北市永和區福和里6鄰中正路６０２巷１號三樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區福和里6鄰中正路６０２巷１號三樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 39,
    "name": "陸昌壽",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F100929131",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "前溪里",
    "householdAddress": "新北市永和區前溪里7鄰保福路一段９２號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區前溪里7鄰保福路一段９２號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 40,
    "name": "鄧志雄",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F104262771",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 41,
    "name": "唐紹烈",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F104254537",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "安和里",
    "householdAddress": "新北市永和區安和里9鄰水源街４１號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區安和里9鄰水源街４１號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 42,
    "name": "柯雪月",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "S201565900",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "水源里",
    "householdAddress": "新北市永和區水源里20鄰保平路２０３巷２號八樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區水源里20鄰保平路２０３巷２號八樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 43,
    "name": "陳錦?",
    "gender": null,
    "birthDate": "1924-01-01",
    "nationalId": "F203653896",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 44,
    "name": "吳杏元",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "R202944897",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "河濱里",
    "householdAddress": "新北市永和區河濱里16鄰環河東路三段５２巷２弄１２號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區河濱里16鄰環河東路三段５２巷２弄１２號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 45,
    "name": "馬克儉",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F100839856",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民權里",
    "householdAddress": "新北市永和區民權里22鄰民生路４６巷２４號十二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民權里22鄰民生路４６巷２４號十二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 46,
    "name": "汪饒世珍",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F202515226",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "水源里",
    "householdAddress": "新北市永和區水源里7鄰永貞路３３２巷２２號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區水源里7鄰永貞路３３２巷２２號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 47,
    "name": "楊秀治",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "K200071145",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "保安里",
    "householdAddress": "新北市永和區保安里28鄰中山路一段３２８巷５號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區保安里28鄰中山路一段３２８巷５號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 48,
    "name": "陳李銀",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "A203054334",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民樂里",
    "householdAddress": "新北市永和區民樂里19鄰民樂街５２號五樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民樂里19鄰民樂街５２號五樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 49,
    "name": "張邱軟",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F200971557",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "大同里",
    "householdAddress": "新北市永和區大同里4鄰新生路１５１號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區大同里4鄰新生路１５１號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 50,
    "name": "王?亭",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "A110362723",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "文化里",
    "householdAddress": "新北市永和區文化里16鄰文化路１３７巷７弄１０號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區文化里16鄰文化路１３７巷７弄１０號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 51,
    "name": "劉忠正",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F100957662",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "智光里",
    "householdAddress": "新北市永和區智光里25鄰中正路８６巷４號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區智光里25鄰中正路８６巷４號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 52,
    "name": "郭阿嬌",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "U200222435",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永成里",
    "householdAddress": "新北市永和區永成里11鄰新生路５３巷２弄１４號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永成里11鄰新生路５３巷２弄１４號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 53,
    "name": "鄭祥裕",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F104263867",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "店街里",
    "householdAddress": "新北市永和區店街里3鄰秀朗路一段４５號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區店街里3鄰秀朗路一段４５號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 54,
    "name": "馬志偉",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F104266091",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 55,
    "name": "江桂英",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "G201259775",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永福里",
    "householdAddress": "新北市永和區永福里17鄰福和路４５號三樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永福里17鄰福和路４５號三樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 56,
    "name": "劉源先",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "A103196433",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "和平里",
    "householdAddress": "新北市永和區和平里14鄰中山路一段１９１巷９弄１２號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區和平里14鄰中山路一段１９１巷９弄１２號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 57,
    "name": "陳榮黨",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "A103247971",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "得和里",
    "householdAddress": "新北市永和區得和里23鄰中正路３５２號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區得和里23鄰中正路３５２號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 58,
    "name": "曹定和",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "E100121885",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民治里",
    "householdAddress": "新北市永和區民治里19鄰民有街１號五樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民治里19鄰民有街１號五樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 59,
    "name": "呂樹木",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F100808048",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "潭安里",
    "householdAddress": "新北市永和區潭安里11鄰中正路８９號八樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區潭安里11鄰中正路８９號八樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 60,
    "name": "袁良",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F104254475",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 61,
    "name": "王干春寶",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "A202678090",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "上溪里",
    "householdAddress": "新北市永和區上溪里1鄰永和路二段２０９號五樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區上溪里1鄰永和路二段２０９號五樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 62,
    "name": "李秀竹",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "S201044755",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民權里",
    "householdAddress": "新北市永和區民權里11鄰民權路４９巷５弄２４號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民權里11鄰民權路４９巷５弄２４號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 63,
    "name": "吳林菊榮",
    "gender": null,
    "birthDate": "1925-01-01",
    "nationalId": "F202489829",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永貞里",
    "householdAddress": "新北市永和區永貞里4鄰福和路１８３巷１號六樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永貞里4鄰福和路１８３巷１號六樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 64,
    "name": "鄭李安梅",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "S202190256",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀成里",
    "householdAddress": "新北市永和區秀成里13鄰民樂街１７巷５號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀成里13鄰民樂街１７巷５號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 65,
    "name": "張盧偉",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "Y200493507",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "智光里",
    "householdAddress": "新北市永和區智光里32鄰中正路２巷７號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區智光里32鄰中正路２巷７號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 66,
    "name": "陸健麟",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F104424057",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 67,
    "name": "陳宗良",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F104424842",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀成里",
    "householdAddress": "新北市永和區秀成里3鄰成功路一段４３巷９號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀成里3鄰成功路一段４３巷９號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 68,
    "name": "楊幼君",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "K200591188",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 69,
    "name": "張林反",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "Q200933000",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "河堤里",
    "householdAddress": "新北市永和區河堤里10鄰環河西路一段８７之２號二十四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區河堤里10鄰環河西路一段８７之２號二十四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 70,
    "name": "張志義",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "A104029262",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "河濱里",
    "householdAddress": "新北市永和區河濱里9鄰福和路７巷１６弄２號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區河濱里9鄰福和路７巷１６弄２號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 71,
    "name": "郭浩然",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "A102324068",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "福林里",
    "householdAddress": "新北市永和區福林里17鄰豫溪街１６２巷１０號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區福林里17鄰豫溪街１６２巷１０號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 72,
    "name": "董如珍",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F200918032",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "河堤里",
    "householdAddress": "新北市永和區河堤里17鄰文化路９０巷３２弄１３號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區河堤里17鄰文化路９０巷３２弄１３號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 73,
    "name": "陸振謙",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F104267123",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "中溪里",
    "householdAddress": "新北市永和區中溪里1鄰和平街７６巷８弄１２號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區中溪里1鄰和平街７６巷８弄１２號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 74,
    "name": "張陳?",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "C200269755",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "民治里",
    "householdAddress": "新北市永和區民治里23鄰民有街２３巷２５號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區民治里23鄰民有街２３巷２５號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 75,
    "name": "陸劉小藕",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "C200434930",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "新?里",
    "householdAddress": "新北市永和區新?里9鄰文化路１９２巷４弄１之１號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區新?里9鄰文化路１９２巷４弄１之１號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 76,
    "name": "施陳淑貞",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "E201354531",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "雙和里",
    "householdAddress": "新北市永和區雙和里4鄰中和路４２１巷２４號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區雙和里4鄰中和路４２１巷２４號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 77,
    "name": "蔣發初",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F102043849",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永福里",
    "householdAddress": "新北市永和區永福里15鄰福和路２９號四樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永福里15鄰福和路２９號四樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 78,
    "name": "鄭李世英",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "A200854832",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 79,
    "name": "林何梅英",
    "gender": null,
    "birthDate": "1926-01-01",
    "nationalId": "F200159837",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "得和里",
    "householdAddress": "新北市永和區得和里22鄰中正路３６８巷１０弄２號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區得和里22鄰中正路３６８巷１０弄２號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 80,
    "name": "孫廣義",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "A104726140",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "光明里",
    "householdAddress": "新北市永和區光明里5鄰中正路６５４巷１１號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區光明里5鄰中正路６５４巷１１號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 81,
    "name": "曾輝",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "C100335850",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "秀元里",
    "householdAddress": "新北市永和區秀元里18鄰得和路３７３巷３１弄１２號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區秀元里18鄰得和路３７３巷３１弄１２號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 82,
    "name": "何安寬",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F104422875",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 83,
    "name": "施愛珠",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F200974978",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "光復里",
    "householdAddress": "新北市永和區光復里9鄰光復街２巷１６弄４９號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區光復里9鄰光復街２巷１６弄４９號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 84,
    "name": "孫德隆",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "A102819624",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "水源里",
    "householdAddress": "新北市永和區水源里13鄰永貞路２８７巷２弄１２號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區水源里13鄰永貞路２８７巷２弄１２號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 85,
    "name": "孫榮",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F102895085",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "光復里",
    "householdAddress": "新北市永和區光復里9鄰光復街２巷１６弄２９號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區光復里9鄰光復街２巷１６弄２９號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 86,
    "name": "馮莊",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "C100129692",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "豫溪里",
    "householdAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區豫溪里15鄰竹林路２００之１號（新北市永和戶政事務所）",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 87,
    "name": "崔志誠",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F200809789",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "安和里",
    "householdAddress": "新北市永和區安和里14鄰雙和街２０巷１號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區安和里14鄰雙和街２０巷１號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 88,
    "name": "陸南君",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "T200255031",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永樂里",
    "householdAddress": "新北市永和區永樂里9鄰自由街３９號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永樂里9鄰自由街３９號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 89,
    "name": "楊蘭芝",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F200945780",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "水源里",
    "householdAddress": "新北市永和區水源里8鄰永貞路３２６號六樓之１",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區水源里8鄰永貞路３２６號六樓之１",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 90,
    "name": "李君鼎",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F104258759",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "信義里",
    "householdAddress": "新北市永和區信義里10鄰永和路二段９５號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區信義里10鄰永和路二段９５號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 91,
    "name": "賀沛泉",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F104265174",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "勵行里",
    "householdAddress": "新北市永和區勵行里11鄰勵行街２９巷５號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區勵行里11鄰勵行街２９巷５號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 92,
    "name": "周德瓊",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F202470053",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "仁愛里",
    "householdAddress": "新北市永和區仁愛里4鄰文化路１１３巷３８弄２號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區仁愛里4鄰文化路１１３巷３８弄２號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 93,
    "name": "陳快",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "H200283090",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "智光里",
    "householdAddress": "新北市永和區智光里3鄰民有街１０巷３號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區智光里3鄰民有街１０巷３號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 94,
    "name": "陳復禮",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F128718529",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永貞里",
    "householdAddress": "新北市永和區永貞里5鄰永安街２４號六樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永貞里5鄰永安街２４號六樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 95,
    "name": "楊河溪",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F102902307",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "永樂里",
    "householdAddress": "新北市永和區永樂里5鄰永和路一段１８巷１０號二樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區永樂里5鄰永和路一段１８巷１０號二樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 96,
    "name": "陳漢光",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F102911397",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "網溪里",
    "householdAddress": "新北市永和區網溪里3鄰光復街４０號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區網溪里3鄰光復街４０號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 97,
    "name": "李張瑞娣",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F200974996",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "復興里",
    "householdAddress": "新北市永和區復興里2鄰永和路二段２７６巷１４號三樓",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區復興里2鄰永和路二段２７６巷１４號三樓",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 98,
    "name": "劉漢",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "H101512267",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "文化里",
    "householdAddress": "新北市永和區文化里12鄰文化路１３７巷１６號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區文化里12鄰文化路１３７巷１６號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 99,
    "name": "沈林三妹",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F200291563",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "忠義里",
    "householdAddress": "新北市永和區忠義里6鄰環河西路二段５３號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區忠義里6鄰環河西路二段５３號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 100,
    "name": "洪智朗",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "T100437022",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "前溪里",
    "householdAddress": "新北市永和區前溪里6鄰和平街５４巷５弄８號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區前溪里6鄰和平街５４巷５弄８號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  },
  {
    "sourceRowNumber": 101,
    "name": "范泗英",
    "gender": null,
    "birthDate": "1927-01-01",
    "nationalId": "F203564572",
    "phone": null,
    "mobilePhone": null,
    "lineIdStatus": "否",
    "lineIdNote": null,
    "emergencyContactName": null,
    "emergencyContactRelationship": null,
    "emergencyContactPhone": null,
    "householdCity": "新北市",
    "householdDistrict": "永和區",
    "householdVillage": "得和里",
    "householdAddress": "新北市永和區得和里6鄰秀朗路一段１９２巷４弄７號",
    "residenceCity": null,
    "residenceDistrict": null,
    "residenceVillage": null,
    "residenceAddress": "新北市永和區得和里6鄰秀朗路一段１９２巷４弄７號",
    "residenceAddressNote": "未住戶籍地址；居住地址為",
    "solitaryStatus": "待訪"
  }
];

function padSerial(index: number): string {
  return String(index + 1).padStart(6, "0");
}

function buildCaseCode(index: number): string {
  return `YH-115-075-${padSerial(index)}`;
}

function getAge(birthDate: string | null): number {
  if (!birthDate) return 75;
  const year = Number(birthDate.slice(0, 4));
  if (!Number.isFinite(year)) return 75;
  return Math.max(75, 2026 - year);
}

function getRiskLevel(age: number): ElderCase["riskLevel"] {
  if (age >= 90) return "high";
  if (age >= 83) return "medium";
  return "low";
}

function buildRequiredVisitorTypes(index: number): ElderCase["requiredVisitorTypes"] {
  if ((index + 1) % 5 === 0) return ["social_affairs", "civil_affairs"];
  if ((index + 1) % 3 === 0) return ["social_affairs"];
  return ["civil_affairs"];
}

export const yh75DemoElderCases: ElderCase[] = sourceRows.map((row, index) => {
  const serial = padSerial(index);
  const age = getAge(row.birthDate);
  const requiredVisitorTypes = buildRequiredVisitorTypes(index);
  const coVisitRequired = requiredVisitorTypes.length > 1;

  return {
    id: `case_yh_075_${serial}`,
    caseCode: buildCaseCode(index),
    name: row.name,
    age,
    gender: row.gender,
    nationalId: row.nationalId,
    phone: row.phone ?? row.mobilePhone ?? "未提供",
    mobilePhone: row.mobilePhone,
    address: row.residenceAddress || row.householdAddress,
    district: row.residenceDistrict ?? row.householdDistrict,
    village: row.residenceVillage ?? row.householdVillage,
    serviceUnit: "永和區公所",
    lineIdStatus: row.lineIdStatus,
    lineIdNote: row.lineIdNote,
    emergencyContactName: row.emergencyContactName,
    emergencyContactRelationship: row.emergencyContactRelationship,
    emergencyContactPhone: row.emergencyContactPhone,
    householdCity: row.householdCity,
    householdDistrict: row.householdDistrict,
    householdVillage: row.householdVillage,
    householdAddress: row.householdAddress,
    residenceCity: row.residenceCity,
    residenceDistrict: row.residenceDistrict,
    residenceVillage: row.residenceVillage,
    residenceAddress: row.residenceAddress,
    residenceAddressNote: row.residenceAddressNote,
    solitaryStatus: row.solitaryStatus,
    sourceSheetName: "75歲以上",
    sourceRowNumber: row.sourceRowNumber,
    importBatchCode: yh75DemoImportBatchCode,
    importVisitResult: null,
    importVisitorName: null,
    requiredVisitorTypes,
    coVisitRequired,
    riskLevel: getRiskLevel(age),
    status: "assigned",
  };
});

export const yh75DemoVisitSchedules: VisitSchedule[] = yh75DemoElderCases.map((elderCase, index) => {
  const serial = padSerial(index);
  const needsCoVisit = elderCase.coVisitRequired;

  return {
    id: `schedule_yh_075_${serial}`,
    workspaceId: "ws_elder_visit_115",
    caseId: elderCase.id,
    visitorId: elderCase.requiredVisitorTypes.includes("civil_affairs")
      ? "visitor_yh_civil"
      : "visitor_yh_social",
    coVisitorId: needsCoVisit ? "visitor_yh_social" : null,
    visitDate: `2026-06-${String((index % 20) + 1).padStart(2, "0")}T09:00:00+08:00`,
    visitAttempt: 1,
    status: "pending",
    assignmentReason: "永和 75 歲以上前 100 筆試匯入：依里別、訪員身分與工作量進行派案測試。",
    requiredFormTemplateIds: [
      "gov_social_worker_confidentiality_115",
      "gov_civil_affairs_confidentiality_115",
      "gov_personal_data_consent_115",
      "gov_care_visit_115",
    ],
  };
});
